---
version: '3.7'
services:

    prestashop:
      build: 
        context: prestashop
        dockerfile: Dockerfile
        args:
        - PRESTASHOP_VERSION=1.7.6.2
      environment:
        PS_DOMAIN: "localhost:8081"
        DB_SERVER: db
        DB_PORT: "3306"
        DB_USER: prestashop
        DB_PASSWORD: prestashop
        DB_NAME: prestashop
        DB_CLEAR: '0'
        DB_CREATE: '1'
        DB_PREFIX: "ps_"
        PS_DIR_INSTALL: install1234
        PS_DIR_ADMIN: admin1234
        PS_LANGUAGE: en
        PS_TIMEZONE: "Europe/London"
        PS_SHOP_NAME: "test shop"
        PS_SHOP_COUNTRY: en
        PS_FIRSTNAME: John
        PS_LASTNAME: Doe
        PS_PASSWORD: testshop123
        PS_EMAIL: "jdoe@foo.bar"
        PS_NEWSLETTER: '0'
        PS_SSL: '0'
        PHP_MEMORY_LIMIT: 256M
        PHP_MAX_EXECUTION_TIME: "200"
        PHP_MAX_INPUT_TIME: "60"
      expose:
      - "9000"
      volumes:
      - app:/app
      depends_on:
      - db
      restart: unless-stopped

    web:
      build: web
      environment:
        PS_DOMAIN: "localhost:8081"
        PS_DIR_INSTALL: install1234
        PS_DIR_ADMIN: admin1234
      ports:
      - "8081:80"
      # - "443:443"
      volumes:
      - app:/app:rw
      depends_on:
      - prestashop
      restart: unless-stopped

    db:
      image: mariadb:latest
      environment:
        MYSQL_ROOT_PASSWORD: supercow
        MYSQL_DATABASE: prestashop
        MYSQL_USER: prestashop
        MYSQL_PASSWORD: prestashop
      volumes:
      - ./db/config:/etc/mysql/conf.d
      - db-data:/var/lib/mysql
      restart: unless-stopped

    elasticsearch:
      #restart: unless-stopped
      #environment:
      #  - ES_JAVA_OPTS=-Xms2g -Xmx2g
      # mem_limit: 4g
      # memswap_limit: 4g
      build:
        context: ./elasticsearch
        dockerfile: Dockerfile
        args:
          - CEREBRO_VERSION=0.7.2
      container_name: elasticsearch
      entrypoint: /usr/share/elasticsearch/start
      ports:
        - "9200:9200" # Elasticsearch
        - "9000:9000" # Cerebro
      ulimits:
        memlock:
          soft: -1
          hard: -1
        #nofile:
        #  soft: 65536
        #  hard: 65536
      #cap_add:
      #  - IPC_LOCK
      volumes:
      - esdata:/usr/share/elasticsearch/data

    kibana:
      image: docker.elastic.co/kibana/kibana:7.0.1
      container_name: kibana
      ports:
      - 5601:5601
      depends_on:
      - elasticsearch

    #manticoresearch:
    #  build: manticoresearch
    #  ports:
    #  - 9306:9306
    #  volumes:
    #  - mtdata:/var/lib/manticore/data
    #  - mtdata:/var/log/manticore
    #  - ${PWD}/manticoresearch/sphinx.conf:/etc/sphinxsearch/sphinx.conf

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
      # - pma_arbitrary=1
      # - pma_host=mariadb
        PMA_HOST: "mariadb"
        PMA_USER: ${MYSQL_USER}
        PMA_PASSWORD: ${MYSQL_PASSWORD}
      depends_on:
      - db
      ports:
      - 8080:80

    mailhog:
      image: mailhog/mailhog:v1.0.0
      ports:
      - 1025:1025
      - 4025:8025
      #networks:
      #- back-tier
      #- front-tier

volumes:
    app:
      #driver: local
      #driver_opts:
      #  type: none
      #  o: bind
      #  device: ${PWD}/httpdocs
    db-data:
    esdata:
      driver: local
    mtdata:
      driver: local

#networks:
#  front-tier:
#    driver: bridge
#  back-tier:
#    driver: bridge
#  elk:
#    driver: bridge


### Refs
# - https://github.com/tonyyb/docker-prestashop-php-apache/blob/master/docker-compose.yml
# - https://github.com/tomas862/docker-prestashop
# - https://github.com/yobasystems/alpine-prestashop
# - https://github.com/mathieulesniak/prestashop-php7-nginx-docker
# - https://github.com/youngmikee/prestashop-docker-testshop
# - https://github.com/jagui/prestashop-docker-debugging/blob/master/docker/docker-compose.yml
