name: prestashop-vue
display_name: Starter Theme
version: 3.0.0
author:
  name: "PrestaShop Team"
  email: "pub@prestashop.com"
  url: "http://www.prestashop.com"

meta:
  compatibility:
      from: 1.7.2.0
      to: ~

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three Columns
      description: One large central column and 2 side columns.
    layout-left-side-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-side-column:
      name: Two Columns, small right column
      description: Two columns with a small right column

assets:
  css:
    all:
      - id: font-awesome
        path: ../_libraries/font-awesome/css/font-awesome.min.css
        media: all
        priority: 10

  js:
    all:
      - id: vue-carousel
        path: assets/js/vue-carousel.min.js
        media: all
        priority: 0

global_settings:
  configuration:
    PS_QUICK_VIEW: true

  hooks:
    custom_hooks:
      - name: displayFooterBefore
        title: displayFooterBefore
        description: Add a widget area above the footer

    modules_to_hook:
      displayNav:
        - ps_contactinfo
        - ps_languageselector
        - ps_currencyselector
      displayTop:
        - ps_searchbar
        - ps_customersignin
        - ps_shoppingcart
      displayHome:
        - ps_imageslider
        - ps_specials
        - ps_featuredproducts
        - ps_banner
        - ps_bestsellers
      displayFooterBefore:
        - blockreassurance
      displayFooter:
        - ps_contactinfo
        - ps_linklist
        - ps_customeraccountlinks
      displayNavFullWidth:
        - ps_mainmenu
        - blockreassurance
      displayTopColumnFullWidth:
      displayOrderConfirmation2:
      displayCheckoutTop:
        - ps_searchbar

  image_types:
    cart_default:
      width: 80
      height: 80
      scope: [products]
    small_default:
      width: 150
      height: 150
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 350
      height: 350
      scope: [products, categories, manufacturers, suppliers]
    large_default:
      width: 800
      height: 800
      scope: [products]
    home_default:
      width: 300
      height: 300
      scope: [products]
    category_default:
      width: 960
      height: 350
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]

theme_settings:
  default_layout: layout-full-width

  layouts:
    category: layout-left-side-column
    best-sales: layout-left-side-column