kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: database
  creationTimestamp:
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp:
      labels:
        service: database
    spec:
      containers:
      - name: database
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "P15Oe4EP9gziWzOY4mD"
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          requests:
              cpu: 50m
              memory: 100Mi
          limits:
            cpu: 400m
            memory: 400Mi
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-claim
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 2


status: {}
