kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-data-disk
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: "mysql-data-disk"
    fsType: "ext4"
