kind: Service
apiVersion: v1
metadata:
  name: database
  creationTimestamp:
  labels:
    service: database
spec:
  ports:
  - name: '3306'
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    service: database
status:
  loadBalancer: {}
