kind: PersistentVolume
apiVersion: v1
metadata:
  name: prestashop-data-disk
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: "prestashop-data-disk"
    fsType: "ext4"
