kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prestashop-data-claim
  annotations:
      volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
