kind: Service
apiVersion: v1
metadata:
  name: web
  creationTimestamp:
  labels:
    service: web
spec:
  ports:
  - name: '8080'
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    service: web
  type: LoadBalancer
status:
  loadBalancer: {}
